#spring.application.name=demo

# importa o arquivo de segredos se ele existir (o 'optional:' evita erro se o arquivo faltar)
spring.config.import=optional:application-secret.properties
spring.datasource.url=jdbc:postgresql://localhost:5432/MarlonDB
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres

# configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# opcional, mas recomendado para garantir o dialeto correto
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

